name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: GraphTest
      id: arrayhelpertest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GraphTest
        command: mvn -B test -Dtest=GraphTest
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ARRAYHELPERTEST_RESULTS: "${{steps.arrayhelpertest.outputs.result}}"
        STRINGHELPERTEST_RESULTS: "${{steps.stringhelpertest.outputs.result}}"
        STUDENTTEST_RESULTS: "${{steps.studenttest.outputs.result}}"
        UNIVERSITYTEST_RESULTS: "${{steps.universitytest.outputs.result}}"
      with:
        runners: arrayhelpertest,stringhelpertest,studenttest,universitytest
